# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 347c161a3cb89d0ce3e34b29c12d0b1adac6a78f6a5e6c2fd32e36a350a40ee7b420897cf18f174ef3ef0539603dc377727c09e8892633ac4d3f6251fd33289f

test:
  secret_key_base: 4682af853691a4d2a41d5e1993e7c66916c868fa84b7f5b9d1e7d3ac25c45c1e993caff6362d375372297eb9793d17622a74b5f6ad72f6a64d7833186a40fc9b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
